### ISSUE TITLE
Playground- Default code contents

### ISSUE THREAD

**Issue by jamesnw** [oddbird/sass-site#80]
Default code contents on initial Playground load (if not following a direct link with existing contents)

What should code contents be?

**Comment by mirisuzanne** [comment]
@jamesnw I suggested a few edits to your default, but also found this as the first example on the `/learn` page, and think it would be enough on it's own probably? 

```scss
$font-stack: Helvetica, sans-serif;
$primary-color: #333;

body {
  font: 100% $font-stack;
  color: $primary-color;
}
```
